### ISSUE TITLE
hi,could you please take a look at this question ? Thank you very very very very very much. 

### ISSUE THREAD

**Issue by guotong1988** [belgattitude/php-java-bridge#1]
http://stackoverflow.com/questions/36840618/php-java-bridge-usage-of-extend

**Comment by belgattitude** [comment]
No Idea right now, but I'm gonna work on the code in the following weeks... 

In any case don't rely too much on the Java.inc client, I've reworked it on the [soluble-japha](https://github.com/belgattitude/soluble-japha) repo.
