### ISSUE TITLE
Poorly checked doGet method in PhpJavaServlet.java

### ISSUE THREAD

**Issue by belgattitude** [belgattitude/php-java-bridge#12]
I let it for future review:

As seen in  [PhpJavaServlet.java](https://github.com/belgattitude/php-java-bridge/blob/develop/src/main/java/io/soluble/pjb/servlet/PhpJavaServlet.java). 

```java
    /**
     * For backward compatibility
     */
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res)
            throws ServletException, IOException {
        String uri = req.getRequestURI();
        req.getRequestDispatcher(uri.substring(0, uri.length() - 10)).forward(req, res);
    }
```

Figure out why and how to ensure that `uri.length() - 10` not breaking everyhting...

**Comment by cplerch** [comment]
Could of course be dangerous, depending of the uri format.
But that's more a question of general code quality to be dealed with later
on.
As far as I have seen there are hundreds of issues like this in the code.
I have only started to address a few of them which came into my view by
chance.
Let's first complete this round of function-preseving refactoring work
before addressing quality.

2017-01-24 15:03 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:
