### ISSUE TITLE
Ensure version compat, merge upstream 7.0.1 changes

### ISSUE THREAD

**Issue by belgattitude** [belgattitude/php-java-bridge#49]
From the 7.0.1 changelog

**7.0.1** 2017-02-25  <jostb@intern> 7.0.1
> This release includes work on PHPDebugger which was removed from the soluble fork
>  for licence issue. It was relicensed upstream to `GPL+Classpath exception`... 
> Changed linked to it have been skipped. If support needed open an issue.

- [x] `skipped` PhpDebugger.inc: Removed
- [x] `merged_in_legacy` Client.inc: Warning fixed.
- [x] **`skipped`** skipped PHPDebugger.php changes due to licensing (GPL+classpath)
- [x] **`skipped`** skipped changes about debugger inclusion -> Util.java, FCGIConnectionFactory.java, IFCGIProcessFactory.java, NPChannelFactory.java, SocketChannelFactory.java, CGIRunner.java, FCGIProcess.java, FastCGIProxy.java, ContextLoaderListener.java, FCGIProcess.java, FastCGIServlet.java: Use PHPDebuger.php
-----------
**6.2.2** 2017-02-01  <jostb@intern> 
- [x] `merged` BUGFIX - WriterOutputStream.java: Fixed crash.

-----------
**6.2.2** 2017-01-30  <jostb@intern> 

- [x] `merged_in_legacy` Protocol.inc, PHPDebugger.php, PHPDebugger.inc, Parser.inc, Options.inc, NativeParser.inc, JavaProxy.inc, JavaBridge.inc, GlobalRef.inc, Client.inc: Changed constructor

-----
Changed files

File php-java-bridge/CVS_RELEASE.sh changed from revision 1.31 to 1.38
File php-java-bridge/ChangeLog changed from revision 1.238 to 1.241
File php-java-bridge/NEWS changed from revision 1.89 to 1.92
File php-java-bridge/VERSION changed from revision 1.152 to 1.155
File php-java-bridge/build.xml changed from revision 1.13 to 1.14
File php-java-bridge/php-java-bridge.spec changed from revision 1.173 to 1.179
File php-java-bridge/security/module/php-java-bridge-tomcat.te changed from revision 1.2 to 1.3
File php-java-bridge/security/module/php-java-bridge.te changed from revision 1.6 to 1.7
File php-java-bridge/server/META-INF/java/Client.inc changed from revision 1.35 to 1.37
File php-java-bridge/server/META-INF/java/GlobalRef.inc changed from revision 1.5 to 1.6
File php-java-bridge/server/META-INF/java/JavaProxy.inc changed from revision 1.41 to 1.43
File php-java-bridge/server/META-INF/java/NativeParser.inc changed from revision 1.10 to 1.11
File php-java-bridge/server/META-INF/java/PHPDebugger.inc is removed; 2015.12.31.23.00.00 revision 1.12
File php-java-bridge/server/META-INF/java/PHPDebugger.php changed from revision 1.17 to 1.18
File php-java-bridge/server/META-INF/java/Parser.inc changed from revision 1.5 to 1.6
File php-java-bridge/server/META-INF/java/Protocol.inc changed from revision 1.51 to 1.52
File php-java-bridge/server/META-INF/java/SimpleParser.inc changed from revision 1.9 to 1.10
File php-java-bridge/server/php/java/bridge/Util.java changed from revision 1.115 to 1.116
File php-java-bridge/server/php/java/bridge/http/FCGIConnectionFactory.java changed from revision 1.6 to 1.7
File php-java-bridge/server/php/java/bridge/http/IFCGIProcessFactory.java changed from revision 1.7 to 1.8
File php-java-bridge/server/php/java/bridge/http/NPChannelFactory.java changed from revision 1.6 to 1.7
File php-java-bridge/server/php/java/bridge/http/SocketChannelFactory.java changed from revision 1.5 to 1.6
File php-java-bridge/server/php/java/bridge/http/WriterOutputStream.java changed from revision 1.2 to 1.3
File php-java-bridge/server/php/java/script/CGIRunner.java changed from revision 1.36 to 1.37
File php-java-bridge/server/php/java/script/FCGIProcess.java changed from revision 1.3 to 1.4
File php-java-bridge/server/php/java/script/FastCGIProxy.java changed from revision 1.12 to 1.13
File php-java-bridge/server/php/java/servlet/ContextLoaderListener.java changed from revision 1.24 to 1.25
File php-java-bridge/server/php/java/servlet/fastcgi/FCGIProcess.java changed from revision 1.8 to 1.9
File php-java-bridge/server/php/java/servlet/fastcgi/FastCGIServlet.java changed from revision 1.44 to 1.45

**Comment by belgattitude** [comment]
Hi @cplerch 

Just tested the merges from upstream and look fine... I'm about to update the master branch and release a 7.0.0 version. I don't think there's big risk in this one, have you any objections or comment ?

**Comment by cplerch** [comment]
No, looks good to me too.

2017-03-06 12:27 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:

**Comment by belgattitude** [comment]
v7.0.0 released, artifacts published on maven

**Comment by belgattitude** [comment]
Note the changelog

https://github.com/belgattitude/php-java-bridge/releases/tag/7.0.0

And optionally update your soluble/japha to 1.2.0

https://github.com/belgattitude/soluble-japha/releases/tag/1.2.0
