### ISSUE TITLE
How to change port number of php java bridge?

### ISSUE THREAD

**Issue by oanqa** [belgattitude/php-java-bridge#61]
Can we change the default port number ```9267``` to something else?

**Comment by belgattitude** [comment]
I don't think so, at least without recompiling

https://github.com/belgattitude/php-java-bridge/blob/276047656a23a5acb726667becd3fdfdc3160291/src/main/java/io/soluble/pjb/bridge/TCPServerSocket.java#L34

It's a starting port for each context (you generally have only one)... I won't explain in too much details.
 
Personally I would not do it...  docker is cool for that. 

See an old projet https://github.com/belgattitude/jasper-bridge-docker I did. Don't know if it works but can be a base if you want to translate ports....

**Comment by belgattitude** [comment]
I must add I don't really master docker ;)

**Comment by oanqa** [comment]
i'm aware of docker ports mapping, i also using docker for serving java bridge. But in [soluble-japha](https://github.com/belgattitude/soluble-japha/blob/master/src/Soluble/Japha/Bridge/Driver/Pjb62/SimpleHttpTunnelHandler.php#L331-L336) port 9267 is the redirect port from the java-bridge side. So we cannot use port mapping for this use case unless we can change the redirect port from the php client

**Comment by belgattitude** [comment]
Yes indeed, then I don't really know. If you have an idea, I can have a look but for now I'm not using the bridge anymore.

**Comment by oanqa** [comment]
For quick fix, now i'm "force" changing the ```$headers['redirect']``` to the port that we are mapping for the host container

**Comment by belgattitude** [comment]
Yes it's possible,  

Be aware that in the case you deploy multiple javabridge instances on Tomcat or the port is already in use, that number will vary (increment....). From docker/spring boot that should not be an issue.

If you feel the need to have this feature, open a P/R. It's not always easy to get in the code (was refactored) but it should possible to set this at configuration time.

i.e: https://docs.soluble.io/soluble-japha/bridge_connection/#connection-params
